#!/usr/bin/env bash
# This `DEBIAN/postrm` script is run post-uninstallation

set -e

systemctl stop swisstronik-node-v1.0.8                    || true
systemctl disable swisstronik-node-v1.0.8                 || true
rm -f /etc/systemd/system/swisstronik-node-v1.0.8.service || true
rm -r /opt/swisstronik/                                   || true
systemctl daemon-reload                                   || true
