name: Test CI SW mode

on:
  push:
    branches: [ develop, '**-release', 'ci/test-sw' ]
  workflow_dispatch:
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}


jobs:
  test-ci-sw:
    runs-on: ubuntu-22.04
    env:
      SGX_MODE: SW
      VERSION: "1.0.3"
      PRODUCTION_MODE: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: "Install deps"
        run: |
          apt-get install -y protobuf-compiler curl
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest 
          cargo install protobuf-codegen --version "2.8.1" -f

      - name: "Build SW mode"
        run: SGX_MODE=SW make build
      - name: "Test SW mode"
        run: make test-all