name: Test CI SW mode

on:
  push:
    branches: [ develop, '**-release', 'ci/test-sw' ]
  workflow_dispatch:
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}


jobs:
  test-ci-sw:
    runs-on: ubuntu-22.04
    env:
      SGX_MODE: SW
      VERSION: "1.0.4"
      PRODUCTION_MODE: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Retrieve the secret and decode it to a file
        env:
          ENCLAVE_PK_BASE64: ${{ secrets.ENCLAVE_PK_BASE64 }}
        run: |
          rm sgxvm/Enclave_dev_private.pem || true
          rm sgxvm/Enclave_private.pem || true
          echo $ENCLAVE_PK_BASE64 | base64 --decode > sgxvm/Enclave_private.pem
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Test Image
        uses: docker/build-push-action@v4
        with:
          file: ./docker/test-sw.Dockerfile
          context: .
          load: true
          tags: test-sw
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SGX_MODE=SW
            ENCLAVE_HOME="/usr/lib/"
            PRODUCTION_MODE=false
          target: compile-chain
      - name: Run Test Image
        run: |
          docker run -v $GITHUB_WORKSPACE/build:/build test-sw