name: Test CI SW mode

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}


jobs:
  test-ci-sw:
    runs-on: ubuntu-22.04
    env:
      SGX_MODE: SW
      VERSION: "1.0.4"
      PRODUCTION_MODE: false
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Test Image
        uses: docker/build-push-action@v4
        with:
          file: ./docker/test-sw.Dockerfile
          context: .
          load: true
          tags: test-sw
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SGX_MODE=SW
            ENCLAVE_HOME="/usr/lib/"
            PRODUCTION_MODE=false
          target: compile-chain
      - name: Run Test Image
        run: |
          docker run -e CI=true -v $GITHUB_WORKSPACE/build:/build test-sw